# Generated by Django 3.2.7 on 2022-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0002_auto_20220130_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
