# Generated by Django 3.2.7 on 2022-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0004_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
