# Generated by Django 3.2.7 on 2022-01-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0005_alter_userpreferences_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
    ]
