# Generated by Django 3.2.7 on 2022-01-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0006_remove_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthwithfriends.userpreferences'),
            preserve_default=False,
        ),
    ]
