# Generated by Django 3.2.7 on 2022-02-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0010_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='bmi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='profile_picture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weight',
            field=models.BooleanField(default=True),
        ),
    ]
