# Generated by Django 3.2.7 on 2022-02-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0012_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(null=True),
        ),
    ]
