# Generated by Django 3.2.7 on 2022-02-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0013_auto_20220211_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(),
        ),
    ]
