# Generated by Django 4.0.2 on 2022-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0019_userpreferences_first_name_userpreferences_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='height_units',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weight_units',
            field=models.BooleanField(default=True),
        ),
    ]
