# Generated by Django 4.0.2 on 2022-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0020_userpreferences_height_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
    ]
