# Generated by Django 4.0.2 on 2022-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0021_alter_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='avg_calorific_intake',
            field=models.BooleanField(default=True),
        ),
    ]
