# Generated by Django 4.0.2 on 2022-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0024_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
