# Generated by Django 3.2.7 on 2022-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0027_auto_20220428_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='has_accepted',
            field=models.BooleanField(default=0),
        ),
    ]
