# Generated by Django 3.2.7 on 2022-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0028_friendrequest_has_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='has_denied',
            field=models.BooleanField(default=0),
        ),
    ]
