# Generated by Django 3.2.7 on 2022-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthwithfriends', '0030_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.IntegerField(),
        ),
    ]
